### PR TITLE
remove ocean boundaries

### PR DESCRIPTION
**Pull request by pathmapper**
workaround/temporary fix for https://github.com/openmaptiles/positron-gl-style/issues/6

### CODE REVIEW

**Review by anneb — COMMENTED** [review]
in this PR the fill-antialias is changed to false. Shouldn't the fill-antialias remain true and the fill-outline-color be removed instead?

**Comment by pathmapper** [comment]
@anneb you're right, do you want to make a PR or should I modify this one?

**Comment by anneb** [comment]
I've added a PR

**Comment by pathmapper** [comment]
https://github.com/openmaptiles/positron-gl-style/pull/9 is a better approach.

**Pull request closed without merging**
